fixes #157 and other typos/grammar issues
open-contracting/infrastructure pull request #164
Opened 2019-10-25 11:35 UTC by pindec

2019-10-28 01:01 UTC, duncandewhurst requested changes
Changes look good. I found a couple more and corrected them. Did you run a spell checker across the whole prjoect?

Please add a changelog entry.

2019-10-28 15:24 UTC, pindec commented
I've added an issue to spellcheck the whole project #165.

2019-10-28 17:27 UTC, pindec commented
I've updated the changelog.

2019-10-29 04:11 UTC, duncandewhurst approved these changes

2019-10-29 04:11 UTC, merged