fixes #153 add project/relatedProjects array
open-contracting/infrastructure pull request #178
Opened 2019-10-30 21:53 UTC by pindec

fixes #153

2019-10-30 23:05 UTC, duncandewhurst requested changes
Thanks Charlie! Looking really good, just a few things to address. Mainly aligning language with the definition of project in OC4IDS and removing some unneeded bits from the schema.

Please also add `relatedProjects` to the worked example JSON file and implementation guidance page.

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/codelists/relatedProject.csv
> +construction,Construction,The related project is the initial construction of the infrastructure
```suggestion
construction,Construction,The related project is the initial construction of the set of infrastructure assets
```

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/codelists/relatedProject.csv
> +rehabilitation,Rehabilitation,The related project might result in the rehabilitation of the same infrastructure
```suggestion
rehabilitation,Rehabilitation,The related project might result in the rehabilitation of the same set of infrastructure assets
```

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/codelists/relatedProject.csv
> +replacement,Replacement,The related project might result in the replacement of the same infrastructure
```suggestion
replacement,Replacement,The related project might result in the replacement of the same set of infrastructure assets
```

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/codelists/relatedProject.csv
> +expansion,Expansion,The related project might result in the expansion of the same infrastructure
```suggestion
expansion,Expansion,The related project might result in the expansion of the same set of infrastructure assets
```

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +      "description": "The details of projects related by being involved with the same infrastructure as this project. For example, a related project represented under a separate Open Contracting for
Align language with definition of `project` and make example real-world:

```suggestion
      "description": "The details of projects related to the same set of infrastructure assets as this project. For example, to link a project for the replacement of a bridge to the project for its initial construction.",
```

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +            "null"
Remove `null` as this not required in OC4IDS because there is no release model or merging and make `type` a scalar value, i.e. `"type": "array"`

Please remove `null` for the other properties too.

Edit: in fact, since the `relatedProcess` codelist matches the `projectType` codelist and `project/type` is not an array, I think we should only allow one value here (i.e. make it `string` not `array`)

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +        "id": {
Make `id` required:

1. Add a `required` array to the `RelatedProject` object and add `id` to the array
2. Add `"minLength": 1` to the `id` object

See the `Modification` definition for an example.

See [schema conventions - id fields](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/conventions.html#id-fields) in the standard development handbook for why.

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +          "items": {
See above comment, once `"type": "string"` this can be removed.

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +          "description": "The identifier of the related project. If the scheme is 'oc4ids', this must be an Open Contracting for Infrastructure Data Standard project ID.",
Just for brevity:

```suggestion
          "description": "The identifier of the related project. If the scheme is 'oc4ids', this must be an OC4IDS project ID.",
```

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/codelists/relatedProjectScheme.csv
> +oc4ids,Open Contracting for Infrastructure Data Standard project identifier,An OC4IDS project id
```suggestion
oc4ids,OC4IDS project id,An Open Contracting for Infrastructure Data Standard project identifier
```

2019-10-30 23:05 UTC, duncandewhurst commented on docs/reference/schema.md
> +Details of a related project. A project is related when it is involved with the same infrastructure as the current project.
```suggestion
Details of a project related to the same set of infrastructure assets as the current project.
```

2019-10-30 23:05 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +          "description": "The identification scheme used by this cross-reference, using the open [relatedProjectScheme]((https://standard.open-contracting.org/infrastructure/{{version}}/{{lang}}/refe
```suggestion
          "description": "The identification scheme used by this cross-reference, using the open [relatedProjectScheme](https://standard.open-contracting.org/infrastructure/{{version}}/{{lang}}/reference/codelists/#relatedprojectscheme) codelist.",
```

2019-11-13 10:49 UTC, pindec commented
In the example, type is now "expansion" and linked to relatedProject for the original construction.

2019-11-14 05:55 UTC, duncandewhurst approved these changes
Happy for this to be merged once the final comment is addressed.

2019-11-14 05:55 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +            "integer"
Remove 'integer' from `type`, per https://github.com/open-contracting/infrastructure/issues/184

(sorry - I know it was included in the example I suggested!)

2019-11-14 16:39 UTC, jpmckinney commented
I fixed the comment (removing integer type) and made small edits. The most substantive edit is referring to the related projects data as "references" rather than "details" about related projects, since it contains no details.

2019-11-14 16:40 UTC, jpmckinney commented
@duncandewhurst @pindec Feel free to merge if my first commit looks good (my second commit just reorders the new fields, and my last commit fixes a conflict in the changelog).

2019-11-14 22:08 UTC, merged