Adding approval date to budget breakdown
open-contracting/infrastructure pull request #367
Opened 2022-11-02 15:51 UTC by odscrachel

Adding approval date to budget breakdown as per issue #242

2022-11-10 03:20 UTC, duncandewhurst commented
@odscrachel is this ready for review?

2022-11-15 22:17 UTC, duncandewhurst requested changes
Once you've made the suggested changes, please merge `0.9-dev` into this branch and then run `./manage.py pre-commit` to update `_static/i8n.csv`. You'll need to resolve the merge conflict in the changelog first. Thanks!

2022-11-15 22:17 UTC, duncandewhurst commented on docs/reference/changelog.md
> +* [#367](https://github.com/open-contracting/infrastructure/pull/367) - Adding approval date to budget breakdown.
In keeping with other changelog entries, begin with a verb (add) rather than a present participle (adding).

```suggestion
* [#367](https://github.com/open-contracting/infrastructure/pull/367) - Add approval date to budget breakdown.
```

I created a PR to update the changelog style guide: https://github.com/open-contracting/standard-development-handbook/pull/272

2022-11-15 22:17 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +          "description": "The date on which this budget entry was approved. Where documentary evidence for this exists, it may be included among the project documents with [documentType](https://stan
Per the proposal in the issue, reference the field, not the codelist:

```suggestion
          "description": "The date on which this budget entry was approved. Where documentary evidence for this exists, it may be included among the project documents with `.documentType` set to 'budgetApproval'.",
```

2022-11-18 15:12 UTC, merged

2022-11-18 16:22 UTC, jpmckinney commented
I think Duncan meant to merge 0.9-dev into this branch, rather than the other way around, but changes look good.