Add tender.datePublished
open-contracting/infrastructure pull request #379
Opened 2022-11-27 21:42 UTC by neelima-j

**Related issues**

Closes #286 

**Description**

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [ ] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [ ] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, update `docs/reference/schema.md`:

- [ ] Add an entry to the components section
- [ ] Update the `:collapse:` parameter of the `jsonschema` directive for any schemas or sub-schemas that reference the new definition 

If you added a new codelist:

  - [ ] Add an entry to `docs/reference/codelists.md`

2023-02-14 23:13 UTC, duncandewhurst requested changes
Once you've committed my suggestion, you can request a review from James.

2023-02-14 23:13 UTC, duncandewhurst commented on docs/reference/changelog.md
> +* [#379](https://github.com/open-contracting/infrastructure/pull/379) - Add `tender.datePublished`.
```suggestion
* [#379](https://github.com/open-contracting/infrastructure/pull/379) - Add `contractingProcesses.summary.tender.datePublished`.
```

2023-07-24 14:34 UTC, jpmckinney reviewed
One Markdown format issue. Otherwise approved.

2023-07-24 14:34 UTC, jpmckinney commented on docs/reference/changelog.md
> -
This line ~~should~~ +shouldn’t+ be removed.

2023-07-24 20:32 UTC, duncandewhurst commented on docs/reference/changelog.md
> -
Do you mean that the blank line should be reinstated?

2023-07-24 22:17 UTC, jpmckinney commented on docs/reference/changelog.md
> -
Ah yes, missing word “not” :)

2023-07-25 00:52 UTC, duncandewhurst commented on docs/reference/changelog.md
>  * [#378](https://github.com/open-contracting/infrastructure/pull/378) - clarify semantics of `additionalClassifications`.
```suggestion
* [#379](https://github.com/open-contracting/infrastructure/pull/379) - add `contractingProcesses.summary.tender.datePublished`.
* [#378](https://github.com/open-contracting/infrastructure/pull/378) - clarify semantics of `additionalClassifications`.

```

2023-07-25 00:53 UTC, duncandewhurst commented on docs/reference/changelog.md
> -
Fixed in https://github.com/open-contracting/infrastructure/pull/379/commits/6b281f2b4c12b3f9d6f9f810c370482076ce9c1b

2023-07-25 01:27 UTC, merged