Support page wording
open-contracting/infrastructure pull request #381
Opened 2022-12-13 17:38 UTC by odscrachel

Updating support page to include email addresses for OCP and CoST

2022-12-13 20:12 UTC, duncandewhurst requested changes
After committing my suggestion, please request a review from @jpmckinney before merging. Thanks!

2022-12-13 20:12 UTC, duncandewhurst commented on docs/support.md
> +* [opencode@infrastructuretransparency.org](mailto:opencode@infrastructuretransparency.org) for support from CoST - the Infrastructur Transparency Initiative
```suggestion
* [opencode@infrastructuretransparency.org](mailto:opencode@infrastructuretransparency.org) for support from CoST - the Infrastructure Transparency Initiative
```

2022-12-13 21:36 UTC, duncandewhurst commented
@odscrachel please could you redo this PR branching from `0.9` rather than `0.9-dev` so that we can release it without also releasing the changes on `0.9-dev`? Thanks!

2022-12-15 21:35 UTC, jpmckinney commented
Closing in favor of #382. I can then merge 0.9 back into 0.9-dev.

2022-12-15 21:35 UTC, closed without merging