add environment.goals and environmentalGoal.csv
open-contracting/infrastructure pull request #431
Opened 2023-11-14 17:01 UTC by odscjen

**Related issues**

closes #415 

**Description**

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [x] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [x] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, run `./manage.py pre-commit`.

If you added a new codelist:

  - [x] Add an entry to `docs/reference/codelists.md`

2023-11-14 17:25 UTC, odscjen commented
CI / build (push) appears to be stuck, Details is showing

> Requested labels: ubuntu-latest
Job defined at: open-contracting/infrastructure/.github/workflows/ci.yml@refs/heads/415_climate_objectives
Waiting for a runner to pick up this job...
Job is waiting for a hosted runner to come online.

and has been running for almost 18 minutes now so I'm leaving it for the night and hopefully the runner will come online at some point!

@duncandewhurst if it doesn't I'll try and sort it when I'm back in on Thursday. If it does and there's still errors just leave it and I'll sort them on Thursday. If it does and the build passes then please review :)

2023-11-14 21:40 UTC, duncandewhurst requested changes
Happy for you to request a review from James once you've resolved my comments.

2023-11-14 21:40 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +    mapping: 'Project level: Add the relevant code from the environmentalGoal codelist to the `environment.goals` array'
```suggestion
    mapping: 'Project level: Add the relevant codes from the environmentalGoal codelist to the `environment.goals` array'
```

2023-11-14 21:40 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +          "description": "The environmental goals pursued, using the closed environmentalGoal codelist.",
Add link to codelist reference.

```suggestion
          "description": "The environmental goals pursued, using the closed [environmentalGoal codelist](https://standard.open-contracting.org/infrastructure/{{version}}/{{lang}}/reference/codelists/#environmentalgoal).",
```

2023-11-20 22:42 UTC, jpmckinney reviewed
Two small edits, then good to merge.

2023-11-20 22:42 UTC, jpmckinney commented on schema/project-level/project-schema.json
> +      "description": "Information about the environmental and climate impact of the project and actions the project will take to mitigate potentially negative impacts on adjacent populations and habi
"Information about ... **the**"

```suggestion
      "description": "Information about the environmental and climate impacts of the project and the actions the project will take to mitigate potentially negative impacts on adjacent populations and habitats.",
```

2023-11-20 22:42 UTC, jpmckinney commented on schema/project-level/project-schema.json
> +          "description": "The environmental goals pursued, using the closed [environmentalGoal codelist](https://standard.open-contracting.org/infrastructure/{{version}}/{{lang}}/reference/codelists/
We usually put codelist outside the link, though there are some exceptions (which can be corrected).

```suggestion
          "description": "The environmental goals pursued, using the closed [environmentalGoal](https://standard.open-contracting.org/infrastructure/{{version}}/{{lang}}/reference/codelists/#environmentalgoal) codelist.",
```

2023-11-21 09:41 UTC, merged