projectSector.csv: add sustainability sub-sectors
open-contracting/infrastructure pull request #435
Opened 2023-11-20 17:34 UTC by odscjen

**Related issues**

closes #424 

**Description**

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [ ] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [ ] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, run `./manage.py pre-commit`.

If you added a new codelist:

  - [ ] Add an entry to `docs/reference/codelists.md`

2023-11-20 21:44 UTC, duncandewhurst requested changes
Happy for you to request a review from James once my comments are resolved.

2023-11-20 21:44 UTC, duncandewhurst commented on schema/project-level/codelists/projectSector.csv
> +transport.lowCarbon,Low carbon transport,"Low carbon sustainable transport, including urban mobility, cycling, air and water vehicles powered by renewable energy sources."
```suggestion
transport.lowCarbon,Low-carbon transport,"Low-carbon sustainable transport, including urban mobility, cycling, air and water vehicles powered by renewable energy sources."
```

2023-11-20 21:44 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +    mapping: 'Project Level: Add the equivalent code from ProjectSector codelist to the `sector` array.'
```suggestion
    mapping: 'Project Level: Map to `sector`, using the [ProjectSector codelist]((../../reference/codelists.md#projectsector).'
```

2023-11-21 22:08 UTC, jpmckinney reviewed
Improved consistency of energy descriptions.

2023-11-21 22:08 UTC, jpmckinney commented on mapping/sustainability.yaml
> +        - Natural resource management
```suggestion
        - Natural resource management:
```

2023-11-21 22:08 UTC, jpmckinney commented on schema/project-level/codelists/projectSector.csv
> +energy,Energy,"Energy, including electric power generation, and the transmission and distribution of electricity, oil and gas, for example: power plants, power lines, gas pipelines. A more detailed b
Do we use square brackets for substitutions? I'm used to seeing squiggly brackets (braces, {}).

Also, I'm not sure that we need this instruction here, rather than in the instructions for the codelist itself.

The codelist itself should have some instructions. Notably, I think we recommend using both the parent and child codes in cases where a child code is used. That way, a user can still check for "energy" on its own.

2023-11-21 22:08 UTC, jpmckinney commented on schema/project-level/codelists/projectSector.csv
> +energy.wind,Wind energy,Energy obtained by harnessing the movement of the wind.
```suggestion
energy.wind,Wind energy,Energy generated from air movement in Earth's atmosphere.
```

2023-11-21 22:08 UTC, jpmckinney commented on schema/project-level/codelists/projectSector.csv
> +energy.geothermal,Geothermal energy,Heat energy harvested directly from the earth.
Apparently "thermal" is broader than "heat".

```suggestion
energy.geothermal,Geothermal energy,Thermal energy in Earth's crust.
```

2023-11-21 22:08 UTC, jpmckinney commented on schema/project-level/codelists/projectSector.csv
> +energy.solar,Solar energy,Energy the earth receives from the sun in the form of electromagnetic radiation.
```suggestion
energy.solar,Solar energy,Energy generated from electromagnetic radiation from the Sun.
```

2023-11-21 22:08 UTC, jpmckinney commented on schema/project-level/codelists/projectSector.csv
> +energy.biomass,Biomass energy,Energy contained within living or recently living biological organisms.
```suggestion
energy.biomass,Biomass energy,Energy generated from recently living organisms.
```

2023-11-23 11:35 UTC, odscjen commented on schema/project-level/codelists/projectSector.csv
> +energy,Energy,"Energy, including electric power generation, and the transmission and distribution of electricity, oil and gas, for example: power plants, power lines, gas pipelines. A more detailed b
I was just following the pattern in the transport codes where square brackets are used and this instruction is included in the code description. The instruction you mention are also in the description of the `projectSector` field so I'll remove them from the codelist and I'll remove them from 'transport` as well

2023-11-28 20:17 UTC, jpmckinney approved these changes

2023-11-28 20:18 UTC, merged