project-schema.json: add impactCategories and hasImpactAssessment to …
open-contracting/infrastructure pull request #441
Opened 2023-11-21 15:20 UTC by odscjen

…environment

**Related issues**

closes #398 

**Description**

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [ ] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [ ] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, run `./manage.py pre-commit`.

If you added a new codelist:

  - [ ] Add an entry to `docs/reference/codelists.md`

2023-11-21 19:37 UTC, duncandewhurst requested changes
Happy for you to request a review from James once you've resolved my comments and run `update-sustainability-docs`.

2023-11-21 19:37 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +        - set `.environment.hasImpactAssessment` to true.
```suggestion
        - Set `.environment.hasImpactAssessment` to `true`.
```

2023-11-21 19:37 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +        If an environmental impact assessment was not conducted, set `environmental.hasImpactAssessment` to false.
```suggestion
        If an environmental impact assessment was not conducted, set `environmental.hasImpactAssessment` to `false`.
```

2023-11-28 20:29 UTC, jpmckinney approved these changes

2023-11-28 20:31 UTC, merged