project-schema.json: add environment.abatementCost
open-contracting/infrastructure pull request #442
Opened 2023-11-21 15:38 UTC by odscjen

**Related issues**

closes #416 

**Description**

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [ ] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [ ] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, run `./manage.py pre-commit`.

If you added a new codelist:

  - [ ] Add an entry to `docs/reference/codelists.md`

2023-11-21 19:33 UTC, duncandewhurst requested changes
Happy for you to request a review from James once you've resolved my comments and run `update-sustainability-docs`.

2023-11-21 19:33 UTC, duncandewhurst commented on docs/examples/example.json
> +          "amount": 50000,
Minor point, but the example abatement costs that I found when researching this field were much smaller than 50,000 USD.

```suggestion
          "amount": 12.29,
```

2023-11-21 19:33 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +    mapping: Publish the cost in `environment.abatementCost`. If supporting documentation is available, publish in `documents` with `.documentType` set to 'abatementCostMethodology'.
Copy edit and reference common operation.

```suggestion
    mapping: Map to `environment.abatementCost`. If supporting documentation is available, [add a project document](../common.md#add-a-project-document) and set `.documentType` to 'abatementCostMethodology'.
```

2023-11-21 19:33 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +              "amount": 50000,
Per example in the issue.

```suggestion
              "amount": 12.29,
```

2023-11-28 20:21 UTC, jpmckinney approved these changes

2023-11-28 20:26 UTC, merged