project-schema.json: add ConservationMeasure and conservationMeasure.csv
open-contracting/infrastructure pull request #447
Opened 2023-11-23 17:38 UTC by odscjen

**Related issues**

closes #401 

**Description**

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [ ] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [ ] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, run `./manage.py pre-commit`.

If you added a new codelist:

  - [ ] Add an entry to `docs/reference/codelists.md`

2023-11-23 20:35 UTC, duncandewhurst requested changes
Happy for you to request a review from James once my comments are resolved.

2023-11-23 20:35 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +          "wholeListMerge": true
I think we'll need to remove this, depending on the resolution of https://github.com/open-contracting/infrastructure/pull/434#discussion_r1401173099

```suggestion
          "minItems": 1
```

2023-11-23 20:35 UTC, duncandewhurst commented on docs/reference/codelists.md
> +### conservationMeasure
In keeping with the other headings.

```suggestion
### ConservationMeasure
```

2023-11-23 20:35 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +          "type": "string"
```suggestion
          "type": "string",
          "minLength": 1
```

2023-11-23 20:35 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +        For each measure add a `ConservationMeasure` object to the `environment.conservationMeasures` array, set its `.type` according to the matching code in the open [conservationMeasure](../../ref
```suggestion
        For each measure add a `ConservationMeasure` object to the `environment.conservationMeasures` array, set its `.type` according to the open [conservationMeasure](../../reference/codelists.md#conservationmeasure) codelist and map the further explanation to its `.description`.
```

2023-11-24 09:35 UTC, odscjen commented
The error is just another example of no `id` field in an array object, but the test is to be changed as per https://github.com/open-contracting/infrastructure/pull/438#discussion_r1403805949

2023-11-28 21:20 UTC, jpmckinney commented on schema/project-level/codelists/conservationMeasure.csv
> +pollutionReduction,Pollution reduction,"Measures that reduce the level of pollution generated as a direct result of the project. Pollution can include leakage into water courses or soil as well as no
```suggestion
pollutionReduction,Pollution reduction,"Measures that reduce the pollution generated as a direct result of the project. Pollution can include leakage into water courses or soil as well as noise, light, aerosol and gaseous emissions or vibrational nuisance to nearby wildlife populations."
```

2023-11-28 21:20 UTC, jpmckinney commented on schema/project-level/codelists/conservationMeasure.csv
> +soilManagement,Soil management,Measures that integrate sustainable soil management practices according to the Food and Agriculture Organization's Charter and Sustainable Soil Management Criteria.
```suggestion
soilManagement,Soil management,Measures that integrate sustainable soil management practices. For example, the Food and Agriculture Organization's Charter and Sustainable Soil Management Criteria.
```

2023-11-28 21:20 UTC, jpmckinney commented on schema/project-level/codelists/documentType.csv
> +conservationMeasures,Conservation measures,Documentation of measures to be taken to mitigate the project's impact on biodiversity.,OC4IDS
The schema is "protect and enhance" rather than "mitigate the project's impact on"

2023-11-30 16:23 UTC, jpmckinney approved these changes
I committed a small change to align the documentType code description with the field description for conservationMeasures

2023-11-30 16:23 UTC, merged