project-schema.json: add social.inIndigenousLand and .landCompensatio…
open-contracting/infrastructure pull request #448
Opened 2023-11-24 11:49 UTC by odscjen

…nBudget

**Related issues**

closes #407 
closes #408 

**Description**

both small changes so made sense to combine them into a single PR. Removed mention of "in the contract" from the description of `landCompensationBudget` as realised this is likely to be paid by the project, not the supplier and the contract wasn't mentioned by CoST in the original discussion. Also if it is in the contract then this field should be in `contractingProcess.summary.social` rather than just in `social`

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [ ] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [ ] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, run `./manage.py pre-commit`.

If you added a new codelist:

  - [ ] Add an entry to `docs/reference/codelists.md`

2023-11-26 21:36 UTC, duncandewhurst requested changes

2023-11-26 21:36 UTC, duncandewhurst commented on docs/examples/blank.json
> +      "amount": "integer",
```suggestion
      "amount": "number",
```

2023-11-26 21:36 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +        If the project is located in or cuts through Indigenous land:
```suggestion
        If the project is located in or cuts through indigenous land:
```

2023-11-26 21:36 UTC, duncandewhurst commented on mapping/sustainability.yaml
>             2 Add a `Location` object to the `.locations` array, set its `.id` incrementally and set its description to "Indigenous land: <Name> (<Category>)" substituting <Name>  and <Category> for t
```suggestion
        2. Add a `Location` object to the `.locations` array, set its `.id` incrementally and set its description to "Indigenous land: <Name> (<Category>)" substituting <Name>  and <Category> for the name and land category from the Landmark database.
```

2023-11-26 21:36 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +          "description": "The budget allocated for compensation of land.",
'Compensation of land' reads oddly.

```suggestion
          "description": "The budget allocated for land compensation.",
```

2023-11-26 21:36 UTC, duncandewhurst commented on schema/project-level/project-schema.json
> +          "description": "Whether the project is located in or cuts through Indigenous land.",
Not sure why indigenous is capitalised.

```suggestion
          "title": "In indigenous land",
          "description": "Whether the project is located in or cuts through indigenous land.",
```

2023-11-26 21:49 UTC, duncandewhurst commented
I agree that land compensation is not the responsibility of suppliers so I think this belongs at the project level.

Jen is on leave today so, in the interest of expediency, I've committed my own suggestions and run `update-sustainability-docs`.

2023-11-28 20:58 UTC, jpmckinney approved these changes

2023-11-28 21:01 UTC, merged