project-schema.json: add social.healthAndSafety, constructionMaterial…
open-contracting/infrastructure pull request #449
Opened 2023-11-24 12:25 UTC by odscjen

….csv

**Related issues**

closes #405 

**Description**

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [ ] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [ ] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, run `./manage.py pre-commit`.

If you added a new codelist:

  - [ ] Add an entry to `docs/reference/codelists.md`

2023-11-26 21:46 UTC, duncandewhurst requested changes

2023-11-26 21:46 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +        2. Add a further explanation of the material tests to `.social.healthAndSafety.materialTests.description` including the code of the relevant international or national standard the test confor
```suggestion
        2. Add any further explanation of the tests to `.social.healthAndSafety.materialTests.description` including the international or national standards the tests conform to.
```

2023-11-26 21:46 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +                "description": "Tests were conducted of the steel frame and masonry each structure according to ASTM International standards..."
```suggestion
                "description": "Tests were conducted of the steel frame and masonry of each structure according to ASTM International standards..."
```

2023-11-26 21:50 UTC, duncandewhurst commented
Jen is on leave today so, in the interest of expediency, I've committed my own suggestions and run `update-sustainability-docs`.

2023-11-28 20:57 UTC, jpmckinney approved these changes

2023-11-28 20:57 UTC, merged