project-schema.json: deprecate budget.budgetBreakdown, add budget.bud…
open-contracting/infrastructure pull request #450
Opened 2023-11-24 16:08 UTC by odscjen

…getBreakdowns

**Related issues**

**Description**

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [ ] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [ ] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, run `./manage.py pre-commit`.

If you added a new codelist:

  - [ ] Add an entry to `docs/reference/codelists.md`

2023-11-24 16:15 UTC, odscjen commented
currently getting a make error that I cannot figure out! @duncandewhurst as I'm off on Monday if you have the time and want to have a look at this that would be great and help speed things along.

2023-11-26 22:07 UTC, duncandewhurst commented
For some reason, in order for `budget/budgetBreakdowns` to appear in the project schema table (and so for the missing link target to exist) it has to be added to the `:collapse:` option of the jsonschema directive. I've done that so the build error is resolved.

For this PR, since we didn't specify field titles and descriptions etc. in the issue, I think it'll make the most sense for you to request a first review from James in case he has comments on those (he can focus on reviewing only `project-schema.json`) before I review the rest of the PR.

2023-11-28 20:53 UTC, jpmckinney approved these changes
Just one comment that can be easily resolved. Over to @duncandewhurst

2023-11-28 20:53 UTC, jpmckinney commented on schema/project-level/project-schema.json
> +          }
I think we only implement a deprecation policy starting with 1.0. So, simpler to just delete it.

2023-11-30 20:06 UTC, duncandewhurst requested changes
Happy for this to be merged once my comments are resolved.

2023-11-30 20:06 UTC, duncandewhurst commented on docs/reference/changelog.md
> +* [#450](https://github.com/open-contracting/infrastructure/pull/450) - deprecate `budget.budgetBreakdown` in favor of `budget.budgetBreakdowns`
```suggestion
* [#450](https://github.com/open-contracting/infrastructure/pull/450) - deprecate `budget.budgetBreakdown` in favor of `budget.budgetBreakdowns`.
```

2023-11-30 20:06 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +        - Set the budget breakdown's `.sourceParty` to the `.id` and `.name` of the organization.
Copy edit

```suggestion
        1. Get the `BudgetBreakdowns` object in the `budget.budgetBreakdowns` array whose `.description` is "Breakdown by stage". If none exists yet, add a `BudgetBreakdowns` object to the `budget.budgetBreakdowns` array, set its `.id` incrementally and its `.description` to "Breakdown by stage".

        2. For each stage:

           a. Get the `BudgetBreakdown` object in the budget breakdowns' .budgetBreakdown` array whose `.description` is the name of the stage. If none exists yet, add a `BudgetBreakdown` object to the budget breakdowns' .budgetBreakdown` array, set its `.id` incrementally and set its `.description` to the name of the stage.

           b. Get the `Organization` object in `.parties` that represents the funding source. If none exists yet, [add an organization](../common.md#add-an-organization) and add 'funder' to its `.roles`.

           c. Set the budget breakdown's `.sourceParty` to the `.id` and `.name` of the funding source.
```

2023-11-30 20:06 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +                  }
In keeping with the OC4IDS approach of omitting missing data rather than setting fields to "n/a" or similar.

```suggestion
                  }
```

2023-11-30 20:06 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +        4. For each stage, map the amount and currency to the budget breakdown's `.amount`
Copy edit

```suggestion
        1. Get the `BudgetBreakdowns` object in the `budget.budgetBreakdowns` array whose `.description` is "Breakdown by stage". If none exists yet, add a `BudgetBreakdowns` object to the `budget.budgetBreakdowns` array, set its `.id` incrementally and its `.description` to "Breakdown by stage".

        2. For each stage:
 
           a. Get the `BudgetBreakdown` object in the budget breakdowns' .budgetBreakdown` array whose `.description` is the name of the stage. If none exists yet, add a `BudgetBreakdown` object to the budget breakdowns' .budgetBreakdown` array, set its `.id` incrementally and set its `.description` to the name of the stage.

           b. Map to the budget breakdown's `.amount`.
```

2023-11-30 20:06 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +                  }
See comment on previous example.

```suggestion
                  }
```

2023-11-30 20:06 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +        4. For each year, map the amount and currency to the budget breakdown's `.amount`
Copy edit. Map to year to `.period`. Allow for the possibility of non-calendar financial years.

```suggestion
        1. Add a `BudgetBreakdowns` object to the `budget.budgetBreakdowns` array, set its `.id` incrementally and its `.description` to "Breakdown by year of implementation".

        2. For each year:
        
          a. Add a `BudgetBreakdown` object to the budget breakdowns' `.budgetBreakdown` array and set its `.id` incrementally.
          
          b. Map the year's start and end dates to `.period`
          
          c. Map the budget projection to `.amount`.
```

2023-11-30 20:06 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +                    "description": "2024",
See updates to mapping

```suggestion
                    "period": {
                      "2024-01-01T00:00:00Z",
                      "2024-12-31T00:00:00Z"
                    },
```

2023-11-30 20:06 UTC, duncandewhurst commented on mapping/sustainability.yaml
> +                    "description": "2025",
See updates to mapping

```suggestion
                    "period": {
                      "2025-01-01T00:00:00Z",
                      "2025-12-31T00:00:00Z"
                    },
```

2023-12-01 11:04 UTC, merged