update sustainability module mapping and documentType.csv
open-contracting/infrastructure pull request #475
Opened 2024-01-23 15:26 UTC by odscjen

**Related issues**

closes #473 
closes #472 
closes #470 

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [ ] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [ ] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, run `./manage.py pre-commit`.

If you added a new codelist:

  - [ ] Add an entry to `docs/reference/codelists.md`

2024-01-26 22:15 UTC, neelima-j requested changes
There is one comment in the mapping where a change is needed, and two where we need to align with Maria:

- [Climate and disaster risk assessment](https://github.com/open-contracting/infrastructure/pull/475/files/2105171c1fbe066d7e02ba6507904ed6b3569864#r1468134203)

- [Public consultation meetings](https://github.com/open-contracting/infrastructure/pull/475/files/2105171c1fbe066d7e02ba6507904ed6b3569864#r1468186141 )

The rest of the changes have been made as per the issues.

2024-01-26 22:15 UTC, neelima-j commented on mapping/sustainability.yaml
> +    disclosure format: Clarify the type of climate and disaster risks to which the project is exposed to. This tends to be part of the appraisal documents.
```suggestion
    disclosure format: Clarify the type of climate and disaster risks to which the project is exposed. This tends to be part of the appraisal documents.
```
The last 'to' is redundant. @mgraca-prado Would you like to make the change in the data point?

2024-01-26 22:15 UTC, neelima-j commented on mapping/sustainability.yaml
> +    disclosure format: Clarify the project reporting period, it could be quarterly, annually, biannually.
```suggestion
    disclosure format: Clarify the project reporting period. It could be quarterly, annually, biannually.
```
This needs to be changed in the Data elements sheet as well.

2024-01-26 22:15 UTC, neelima-j commented on mapping/sustainability.yaml
> +    disclosure format: Disclose the occurrence of public meetings with communities and impacted groups including the meeting invite, the number of participants, dates and location of these meetings.
```suggestion
    disclosure format: Disclose the occurrence of public meetings with communities and impacted groups including the meeting invite, the number of participants, dates and location of these meetings.
```
@mgraca-prado The wording here is slightly different from your suggested text (placement of the word 'the'), but I'd suggest updating the IDS element to the text above, for grammatical reasons.  

@odscjen Shall we hold off on this change till we hear back from Maria?

2024-01-30 09:06 UTC, odscjen commented on mapping/sustainability.yaml
> +    disclosure format: Disclose the occurrence of public meetings with communities and impacted groups including the meeting invite, the number of participants, dates and location of these meetings.
Given the change was just to improve the grammar I think we can go ahead with the change.

2024-01-30 09:07 UTC, odscjen commented on mapping/sustainability.yaml
> +    disclosure format: Clarify the type of climate and disaster risks to which the project is exposed to. This tends to be part of the appraisal documents.
I've just removed this last 'to' to make the sentence more grammatically correct.

2024-01-31 15:29 UTC, jpmckinney approved these changes

2024-01-31 15:29 UTC, merged