471 environmental measures
open-contracting/infrastructure pull request #476
Opened 2024-02-06 10:36 UTC by odscjen

**Related issues**

closes #471 

**Description**

**Merge checklist**

- [ ] [Log your changes](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html#logging-changes)

If there are changes to `project-schema.json` or `project-package-schema.json`:

- [ ] Update the examples:
  - [ ] `docs/examples/example.json`
  - [ ] `docs/examples/blank.json`
- [ ] Run `./manage.py pre-commit` to update `docs/_static/i8n.csv`

If you added a new definition to the schema, run `./manage.py pre-commit`.

If you added a new codelist:

  - [ ] Add an entry to `docs/reference/codelists.md`

2024-02-12 19:03 UTC, neelima-j requested changes
- 'environmentalMeasures' to be added to documentType 
 - Other changes suggested to match issue discussion.

2024-02-12 19:03 UTC, neelima-j commented on schema/project-level/codelists/environmentalMeasure.csv
> +useNaturalResources,"Environmentally responsible use of land, water and air","Measures that ensure the sustainable and environmentally responsible use of land, water and air by the project."
```suggestion
naturalResourceUse,"Environmentally responsible use of land, water and air","Measures that ensure the sustainable and environmentally responsible use of land, water and air by the project."
```
as per https://github.com/open-contracting/infrastructure/issues/471#issuecomment-1936844236

2024-02-12 19:03 UTC, neelima-j commented on schema/project-level/codelists/environmentalMeasure.csv
> +wasteManagement,Waste Management,"Measures that avoid, reduce, recycle and reuse waste generated as a direct result of the project. When waste is produced, it shall be treated, destroyed or disposed
```suggestion
wasteManagement,Waste Management,"Measures that avoid, reduce, recycle and reuse waste generated as a direct result of the project. When waste is produced, it ought to be treated, destroyed or disposed of in a safe and environmentally sound manner."
```
as per https://github.com/open-contracting/infrastructure/issues/471#issuecomment-1936844236

2024-02-12 19:03 UTC, neelima-j commented on schema/project-level/codelists/environmentalMeasure.csv
> +constructionWasteDisposal,Disposal of construction by-products,"Measures that avoid, reduce, recycle and reuse construction by-products generated as a direct result of the project. When construction
```suggestion
constructionWasteDisposal,Disposal of construction by-products,"Measures that avoid, reduce, recycle and reuse construction by-products generated as a direct result of the project. When construction by-products are produced, they ought to be treated, destroyed or disposed of in a safe and environmentally sound manner."
```
as per https://github.com/open-contracting/infrastructure/issues/471#issuecomment-1936844236

2024-02-12 19:03 UTC, neelima-j commented on schema/project-level/codelists/environmentalMeasure.csv
> +materialSourcing,Environmentally responsible sourcing of materials,"Measures that ensure all project materials are sourced in an environmentally sustainable manner. For example, Leadership in Energy
```suggestion
materialSourcing,Environmentally responsible sourcing of materials,"Measures that ensure all project materials are sourced in an environmentally sustainable manner. For example, Leadership in Energy and Environmental Design (LEED) standards for building materials or Forest Stewardship Council (FSC) standards for wood."
```
Added the word 'standard'.

2024-02-12 19:03 UTC, neelima-j commented on mapping/sustainability.yaml
> +        2. If there is an accompanying document, [add a project document](../common.md#add-a-project-document) and set its [`.documentType`](project-schema.json,/definitions/Document,documentType) to
I think the environmentalMeasures documentType hasn't been added.

2024-02-12 19:03 UTC, neelima-j commented on docs/reference/changelog.md
> +  * [#476](https://github.com/open-contracting/infrastructure/pull/476) - environmentalMeasures
```suggestion
  * [#476](https://github.com/open-contracting/infrastructure/pull/476) - environmentalMeasure
```
The codelist is environmentalMeasure. Similarly, codelist in line 74 should now be climateMeasure.

2024-02-12 19:03 UTC, neelima-j commented on docs/reference/changelog.md
> +    * [#457](https://github.com/open-contracting/infrastructure/pull/457) - 'climateMeasure'
```suggestion
    * [#457](https://github.com/open-contracting/infrastructure/pull/457) - 'climateMeasures'
```
This code is still in the plural in documentType- climateMeasures.

2024-02-15 11:51 UTC, odscjen commented on docs/reference/changelog.md
> +    * [#457](https://github.com/open-contracting/infrastructure/pull/457) - 'climateMeasure'
the documentType I think should still be plural as the document could be detailing multiple measures

2024-02-15 11:52 UTC, odscjen commented on mapping/sustainability.yaml
> +        2. If there is an accompanying document, [add a project document](../common.md#add-a-project-document) and set its [`.documentType`](project-schema.json,/definitions/Document,documentType) to
good catch! that should have been added as part of a previous PR that added a LOT of new codes to documentType

2024-02-15 12:08 UTC, odscjen commented
@jpmckinney this should be the final PR for changes to 0.9.4. Once this is merged we can merge 0.9-dev into 0.9 and then make a start on the Spanish translation of the new bits.

2024-02-15 21:34 UTC, jpmckinney reviewed
Just a few suggestions to make the codelist and schema easier to read.

2024-02-15 21:34 UTC, jpmckinney commented on docs/reference/changelog.md
> +  * [#476](https://github.com/open-contracting/infrastructure/pull/476) - `environment.environmentalMeasures`
Move this into alphabetical order per field name (not issue number).

2024-02-15 21:34 UTC, jpmckinney commented on schema/project-level/codelists/documentType.csv
> +environmentalMeasures,Environmental measures,Documentation of the measures adopted by the project to mitigate or remedy environmental impacts.,OC4IDS
Move this and climateMeasures under conservationMeasures (and order them alphabetically).

2024-02-15 21:34 UTC, jpmckinney commented on schema/project-level/project-schema.json
> +        "environmentalMeasures": {
As with the codelist, move this and climateMeasures under conservationMeasures (and order them alphabetically).

2024-02-16 13:59 UTC, odscjen commented
Thanks @jpmckinney I've made those updates, is this ok to merge now?

2024-02-16 15:06 UTC, jpmckinney approved these changes

2024-02-16 15:06 UTC, merged