0.9.5 release prep
open-contracting/infrastructure pull request #479
Opened 2024-02-27 22:54 UTC by duncandewhurst

* Update the changelog to move the changes made since the 0.9.4 release to the 0.9.5 entry
* Update version numbers

2024-02-28 17:10 UTC, neelima-j requested changes

2024-02-28 17:10 UTC, neelima-j commented on docs/reference/changelog.md
> +    * 'waterManagement'
```suggestion
  * [#475](https://github.com/open-contracting/infrastructure/pull/475) - conservationMeasure:
    * 'airManagement'
    * 'waterManagement'
```

2024-02-29 09:12 UTC, odscjen approved these changes

2024-02-29 16:27 UTC, jpmckinney approved these changes

2024-03-01 02:03 UTC, merged